platform :ios, '18.2'
use_frameworks!

target 'widgetoshinoko' do
  # 必要なPodがあれば追加

  target 'widgetoshinokoTests' do
    inherit! :search_paths
  end

  target 'widgetoshinokoUITests' do
    inherit! :search_paths
  end
end
